import { Quote, Trash2 } from 'lucide-react';
import { contact } from '../data/content';
import Reveal from './Reveal';
import StarRating from './StarRating';
import TestimonialForm from './TestimonialForm';
import useTestimonials from '../hooks/useTestimonials';

export default function Testimonials() {
  const { combined, addTestimonial, removeTestimonial } = useTestimonials();
  return <section className="section-pad relative"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><Reveal className="mx-auto max-w-2xl text-center"><span className="eyebrow justify-center">Client Feedback</span><h2 className="mt-4 font-display text-3xl font-bold text-navy-900 dark:text-white sm:text-4xl">What our clients say</h2></Reveal><div className="mt-14 grid items-start gap-8 lg:grid-cols-[minmax(280px,0.8fr)_1.4fr]"><Reveal variant="left" className="glass-strong rounded-3xl p-7 sm:p-8"><span className="eyebrow">Share Your Experience</span><p className="mt-4 text-xs leading-relaxed text-slate-500 dark:text-slate-400">Feedback you share here is saved on this device only. It is visible to you on this browser, not published to other visitors. <a href={`mailto:${contact.salesEmail}`} className="font-semibold text-electric-500 hover:underline">Email us</a> to have your testimonial featured for everyone.</p><TestimonialForm addTestimonial={addTestimonial} /></Reveal><div className="grid gap-5 md:grid-cols-2">{combined.map((testimonial, index) => <Reveal key={testimonial.id} delay={index * 70} variant={index % 2 ? 'right' : 'up'}><article className={`glass-card flex h-full flex-col rounded-3xl p-6 ${testimonial.placeholder ? 'border-dashed' : ''}`}><div className="flex items-start justify-between gap-3"><Quote className="h-7 w-7 text-electric-400/70" />{testimonial.rating && <StarRating value={testimonial.rating} readOnly size={14} />}</div><p className="mt-4 flex-1 text-sm italic leading-relaxed text-slate-500 dark:text-slate-400">{testimonial.quote}</p>{testimonial.source === 'you' && <div className="mt-4 flex items-center justify-between gap-3"><span className="rounded-full bg-cyan-400/10 px-2.5 py-1 text-[10px] font-semibold text-cyan-600 dark:text-cyan-300">Shared by you on this device</span><button type="button" onClick={() => removeTestimonial(testimonial.id)} aria-label="Delete your feedback" className="text-slate-400 transition-colors hover:text-red-500"><Trash2 className="h-4 w-4" /></button></div>}<div className="mt-5 border-t border-slate-900/5 pt-4 dark:border-white/10"><p className="text-sm font-semibold text-navy-900 dark:text-white">{testimonial.name}</p><p className="text-xs text-slate-400">{[testimonial.role, testimonial.org].filter(Boolean).join(' · ')}</p></div></article></Reveal>)}</div></div></div></section>;
}
