// Explicit icon imports (rather than `import * as Icons`) so the build
// only bundles the ~40 icons this site actually uses instead of the
// entire lucide-react library.
import {
  BarChart3,
  Bell,
  Building2,
  Calculator,
  CalendarCheck2,
  CalendarClock,
  CheckCircle2,
  Clock,
  Cpu,
  Eye,
  EyeOff,
  Factory,
  FileBarChart,
  FileCheck2,
  FileText,
  Fingerprint,
  Globe2,
  HelpCircle,
  KeyRound,
  LineChart,
  Lock,
  Mail,
  Moon,
  Network,
  Scale,
  ScanFace,
  ScanLine,
  ScrollText,
  Server,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Users2,
  UsersRound,
  Wallet,
  Workflow,
  Zap,
} from 'lucide-react';

const registry = {
  BarChart3,
  Bell,
  Building2,
  Calculator,
  CalendarCheck2,
  CalendarClock,
  CheckCircle2,
  Clock,
  Cpu,
  Eye,
  EyeOff,
  Factory,
  FileBarChart,
  FileCheck2,
  FileText,
  Fingerprint,
  Globe2,
  HelpCircle,
  KeyRound,
  LineChart,
  Lock,
  Mail,
  Moon,
  Network,
  Scale,
  ScanFace,
  ScanLine,
  ScrollText,
  Server,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  Users2,
  UsersRound,
  Wallet,
  Workflow,
  Zap,
};

/**
 * Renders a lucide-react icon by name string, so data files can stay
 * plain JS/JSON (icon: 'ShieldCheck') instead of importing components.
 * Add new icon names to the import list + registry above as needed.
 */
export default function Icon({ name, className = '', strokeWidth = 1.75, ...rest }) {
  const Cmp = registry[name] || HelpCircle;
  return <Cmp className={className} strokeWidth={strokeWidth} {...rest} />;
}